# Generated by Django 3.0.4 on 2020-03-28 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200328_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='team',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
