# Generated by Django 3.0.4 on 2020-03-28 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_userprofileinfo_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='team',
            field=models.CharField(max_length=20),
        ),
    ]
