# Generated by Django 3.0.4 on 2020-03-28 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200328_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='projects',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
